apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler-deployment
  labels:
    app: crawler
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crawler
  template:
    metadata:
      labels:
        app: crawler
    spec:
      imagePullSecrets: 
        - name: regcred
      containers:
      - name: crawler
        # image: mongo:latest
        # image: ny40ny40ny/crawler:latest
        image: yuchen2856/crawler:latest
        ports:
        - containerPort: 7878
          name: crawler
        # resources:
        #   requests:
        #     cpu: 1
        #     memory: 1Gi
        #   limits:
        #     cpu: 1
        #     memory: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: crawler-service
  labels:
    app: crawler
spec:
  type: NodePort
  selector:
    app: crawler
  ports:
  - name: crawler-port
    port: 7878
    protocol: TCP
    targetPort: 7878