---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  selector:
    matchLabels:
      visual-app: grafana
      db-app: flask-server
  template:
    metadata:
      labels:
        # app: grafana
        visual-app: grafana
        db-app: flask-server
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
      - name: grafana
        image: grafana/grafana:8.4.4
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
            name: http-grafana
            protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /robots.txt
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 3000
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 250m
            memory: 750Mi
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: shared-data
      - name: flask
        # image: asia.gcr.io/final-project-2-352117/flask_server:latest
        image: gcr.io/PROJECT_ID/FLASK_SERVER_IMAGE:TAG
        volumeMounts:
        - name: shared-data
          mountPath: /var/lib/grafana
        env:
        - name: DB_DIR
          value: "/var/lib/grafana"
        ports:
        - containerPort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler-dpm
  labels:
    app: crawler-dpm
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: crawler
  template:
    metadata:
      labels:
        app: crawler
    spec:
      imagePullSecrets: 
        - name: regcred
      containers:
      - name: crawler-ctn
        # image: mongo:latest
        # image: ny40ny40ny/crawler:latest
        # image: yuchen2856/crawler:latest
        image: gcr.io/PROJECT_ID/CRAWLER_IMAGE:TAG
        ports:
        - containerPort: 7878
          name: crawler-p
        env:
          - name: SERVICE_HOST
            value: "flask-service"
          - name: SERVICE_PORT
            value: "5000"
        # resources:
        #   requests:
        #     cpu: 1
        #     memory: 1Gi
        #   limits:
        #     cpu: 1
        #     memory: 1Gi


---

apiVersion: v1
kind: Pod
metadata:
  name: url-manager-tsmc
  labels:
    app: url-manager-pod
  #namespace: default
spec:
  imagePullSecrets: 
    - name: regcred
  containers:
    - name: url-manager-tsmc
      image: gcr.io/PROJECT_ID/URL_MANAGER_IMAGE:TAG
      ports:
        - name: url-manager-p
          containerPort: 3005
      env:
        - name: SERVICE_HOST
          value: "crawler-service"
        - name: SERVICE_PORT
          value: "7878"
        - name: GOOGLE_KEYWORD
          value: "TSMC"

---

apiVersion: v1
kind: Pod
metadata:
  name: url-manager-asml
  labels:
    app: url-manager-pod
  #namespace: default
spec:
  imagePullSecrets: 
    - name: regcred
  containers:
    - name: url-manager-asml
      image: gcr.io/PROJECT_ID/URL_MANAGER_IMAGE:TAG
      ports:
        - name: url-manager-p
          containerPort: 3005
      env:
        - name: SERVICE_HOST
          value: "crawler-service"
        - name: SERVICE_PORT
          value: "7878"
        - name: GOOGLE_KEYWORD
          value: "ASML"

---

apiVersion: v1
kind: Pod
metadata:
  name: url-manager-appmat
  labels:
    app: url-manager-pod
  #namespace: default
spec:
  imagePullSecrets: 
    - name: regcred
  containers:
    - name: url-manager-appmat
      image: gcr.io/PROJECT_ID/URL_MANAGER_IMAGE:TAG
      ports:
        - name: url-manager-p
          containerPort: 3005
      env:
        - name: SERVICE_HOST
          value: "crawler-service"
        - name: SERVICE_PORT
          value: "7878"
        - name: GOOGLE_KEYWORD
          value: "Applied+Materials"

---

apiVersion: v1
kind: Pod
metadata:
  name: url-manager-sumco
  labels:
    app: url-manager-pod
  #namespace: default
spec:
  imagePullSecrets: 
    - name: regcred
  containers:
    - name: url-manager-sumco
      image: gcr.io/PROJECT_ID/URL_MANAGER_IMAGE:TAG
      ports:
        - name: url-manager-p
          containerPort: 3005
      env:
        - name: SERVICE_HOST
          value: "crawler-service"
        - name: SERVICE_PORT
          value: "7878"
        - name: GOOGLE_KEYWORD
          value: "SUMCO"