---
apiVersion: v1
kind: Service
metadata:
  name: crawler-service
  labels:
    app: crawler
spec:
  type: NodePort
  selector:
    app: crawler
  ports:
    - name: crawler-port
      port: 7878
      protocol: TCP
      targetPort: 7878
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  ports:
  - port: 3000
    name: grafana-port
    protocol: TCP
    targetPort: http-grafana
  - port: 5000
    name: flask-server-port
    protocol: TCP
    targetPort: flask-server
  selector:
    app: grafana
  sessionAffinity: None
  type: LoadBalancer